import { ApiUsers } from './types';

export const mockResponse: ApiUsers = {
	count: 100,
	next: null,
	previous: null,
	results: [
		{
			id: 1,
			first_name: 'David',
			last_name: 'Usman',
			phone_number: '1',
			companies: [
				{
					id: 1,
					name: 'KBG Russia',
					company_type: 'car_energy',
					service_type: 'energy_monitoring',
					phone_number: '1234567890',
					email: 'email@email.com',
					address: 'Address',
					renewal_date: '2022-10-20',
				},
			],
			employee_id: 'SM11098',
			email: 'drakefinn@smarterise.com',
			access_level: 'operation',
			time: 'Sun · 14 April, 04:25 AM',
		},
		{
			id: 2,
			first_name: 'Daniel',
			last_name: 'Osas',
			phone_number: '2',
			companies: [
				{
					id: 2,
					name: 'KBG Russia',
					company_type: 'car_energy',
					service_type: 'energy_monitoring',
					phone_number: '1234567890',
					email: 'email@email.com',
					address: 'Address',
					renewal_date: '2022-10-20',
				},
			],
			employee_id: 'SM23490',
			email: 'godwinife@smarterise.com',
			access_level: 'admin',
			time: 'Sun · 14 April, 04:25 AM',
		},
		{
			id: 3,
			first_name: 'Emmanuel',
			last_name: 'Akpabio',
			phone_number: '3',
			companies: [
				{
					id: 3,
					name: 'KBG Russia',
					company_type: 'car_energy',
					service_type: 'energy_monitoring',
					phone_number: '1234567890',
					email: 'email@email.com',
					address: 'Address',
					renewal_date: '2022-10-20',
				},
			],
			employee_id: 'SM67891',
			email: 'leosimon@smarterise.com',
			access_level: 'finance',
			time: 'Sun · 14 April, 04:25 AM',
		},
		{
			id: 4,
			first_name: 'Jerry',
			last_name: 'Ubrahim',
			phone_number: '4',
			companies: [
				{
					id: 4,
					name: 'KBG Russia',
					company_type: 'car_energy',
					service_type: 'energy_monitoring',
					phone_number: '1234567890',
					email: 'email@email.com',
					address: 'Address',
					renewal_date: '2022-10-20',
				},
			],
			employee_id: 'SM23456',
			email: 'tedcyrus@smarterise.com',
			access_level: 'manager',
			time: 'Sun · 14 April, 04:25 AM',
		},
	],
};
