import { ApiEventLogs } from './types';

export const mockResponse: ApiEventLogs = {
	count: 100,
	next: null,
	previous: null,
	results: [
		{
			id: 1,
			alert_id: 'ABU-235LK',
			site: 'Oshodi',
			// site: 1,
			zone: 'Oshodi',
			district: 'District A',
			activity: 'Overloading',
			time: '04:25 AM Sun - 14 April, 2022',
			status: 'Resolved',
		},
		{
			id: 2,
			alert_id: 'ABU-235LK',
			site: 'Agure',
			// site: 2,
			zone: 'Agure',
			district: 'District B',
			activity: 'Downtime',
			time: '04:25 AM Sun - 14 April, 2022',
			status: 'Resolved',
		},
		{
			id: 3,
			alert_id: 'ABU-235LK',
			site: 'Terise',
			// site: 3,
			zone: 'Terise',
			district: 'District C',
			activity: 'Surge',
			time: '04:25 AM Sun - 14 April, 2022',
			status: 'Resolved',
		},
		{
			id: 4,
			alert_id: 'ABU-235LK',
			site: 'Valley',
			// site: 4,
			zone: 'Valley',
			district: 'District D',
			activity: 'High temperature',
			time: '04:25 AM Sun - 14 April, 2022',
			status: 'Unresolved',
		},
	],
};
