name: smarterise-spa

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  build-spa:
    name: build-spa
    container:
      image: node:18-bullseye-slim
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Yarn install
        run: yarn install
      - name: Yarn build
        run: yarn build
