name: smarterise-spa

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  build-spa:
    name: Build and deploy SPA
    runs-on: ubuntu-20.04
    container:
      image: node:18-bullseye
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install pip and awscli
        uses: apt-get update && apt-get install -y python3-pip && pip3 install awscli
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Yarn install
        run: yarn install
      - name: Yarn build
        run: yarn build
      - name: Deploy to s3
        run: cd dist && aws s3 sync . s3://smarterise-web-app-dev
